name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      # - name: setup nodejs
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "16"
      # - name: setup dependencies
      #   run: |
      #     pip install poetry
      #     poetry install
      # - name: run test
      #   run: poetry run pytest -x
      # - name: build www
      #   working-directory: www
      #   run: |
      #     yarn install
      #     yarn build
      #   env:
      #     # so create-react-app doesn't treat warning as error.
      #     CI: false
      - name: build wheels
        run: poetry build
      - name: upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist
  release:
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/master') || startswith(github.ref, 'refs/heads/dev-ci')"
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist
      - name: test
        run: |
          ls
          ls dist/
      # - name: pypi publish
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_TOKEN }}
      #     skip_existing: true
      #     print_hash: true
